<a href="https://colab.research.google.com/github/Kaushik15101999/workshop/blob/master/HSL2_OEE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline
from IPython.display import display

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
open('/content/drive/My Drive/', 'w')

In [6]:
df = pd.read_csv("/content/drive/My Drive/HSL2 - 15 Report_20191015 070000~20191016 070000 (1).csv")
df

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (229,230) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Sr. NO.        Date      Time  ... Unnamed: 228  Unnamed: 229 Unnamed: 230
0        5809  15-10-2019  07:01:53  ...          NaN           NaN          NaN
1        6720  15-10-2019  07:01:53  ...          NaN           NaN          NaN
2        5696  15-10-2019  07:02:46  ...          NaN           NaN          NaN
3        5697  15-10-2019  07:02:46  ...          NaN           NaN          NaN
4        5694  15-10-2019  07:03:10  ...          NaN  Cycle time:      4.75 sec
...       ...         ...       ...  ...          ...           ...          ...
6927     4674  15-10-2019  23:51:45  ...          NaN           NaN          NaN
6928     4676  15-10-2019  23:51:54  ...          NaN           NaN          NaN
6929     6702  15-10-2019  23:51:54  ...          NaN           NaN          NaN
6930     4677  15-10-2019  23:51:59  ...          NaN           NaN          NaN
6931     4675  15-10-2019  23:52:04  ...          NaN           NaN          NaN

[6932 rows x 231 columns]

In [0]:
df_OEE = df.values

In [8]:
df_OEE

array([[5809, '15-10-2019', '07:01:53', ..., nan, nan, nan],
       [6720, '15-10-2019', '07:01:53', ..., nan, nan, nan],
       [5696, '15-10-2019', '07:02:46', ..., nan, nan, nan],
       ...,
       [6702, '15-10-2019', '23:51:54', ..., nan, nan, nan],
       [4677, '15-10-2019', '23:51:59', ..., nan, nan, nan],
       [4675, '15-10-2019', '23:52:04', ..., nan, nan, nan]], dtype=object)

In [12]:
df_OEE

array([[5809, '15-10-2019', '07:01:53', ..., nan, nan, nan],
       [6720, '15-10-2019', '07:01:53', ..., nan, nan, nan],
       [5696, '15-10-2019', '07:02:46', ..., nan, nan, nan],
       ...,
       [6702, '15-10-2019', '23:51:54', ..., nan, nan, nan],
       [4677, '15-10-2019', '23:51:59', ..., nan, nan, nan],
       [4675, '15-10-2019', '23:52:04', ..., nan, nan, nan]], dtype=object)

In [0]:
df_OEE = df.head(6932)

In [14]:

df_OEE.columns

Index(['Sr. NO.', 'Date', ' Time', ' Prgram Model', ' Variant', ' Custumer No',
       ' Model No', ' Pallet No Front', ' Pallet No Rear 1',
       ' Pallet No Rear 2',
       ...
       ' Batch Code|OP60 Primary Pawl L', ' Batch Code|OP70 Primary Pawl R',
       ' Batch Code|OP80 Auxiliary Pawl L',
       ' Batch Code|OP100 Auxiliary Pawl R', ' Batch Code|OP140 Gear Plate',
       ' Batch Code|OP140 Gear Matel Ring', ' ', 'Unnamed: 228',
       'Unnamed: 229', 'Unnamed: 230'],
      dtype='object', length=231)

In [0]:
df_OEE = [[df_OEE['Date']],[df_OEE[' Time']],[df_OEE[' Position']],[df_OEE[' Line ID']],[df_OEE[' Result']] ]

In [0]:
df_Time = df_OEE[1][0]


In [0]:
n = 6932
df_Time_Sec = np.empty([n,1])
for i in np.arange(0,n):
  ftr = [3600,60,1]
  df_Time_Sec[i] = sum([a*b for a,b in zip(ftr, map(int,df_Time[i].split(':')))])

In [0]:
df_Time_Diff = np.empty([n,1])
for i in np.arange(0,n):
  df_Time_Diff[i] = df_Time_Sec[i]-df_Time_Sec[i-1]

In [0]:
df_Time_Diff = df_Time_Diff[1:n]

In [20]:
df_Time_Diff.shape


(6931, 1)

In [21]:
60611/(60*60)

16.836388888888887

In [0]:
df_Unplanned_Down = 0
for i in np.arange(0,n-1):
  if(df_Time_Diff[i]>60):
    df_Unplanned_Down = df_Unplanned_Down + df_Time_Diff[i]


In [23]:
df_Unplanned_Down

array([19010.])

In [24]:
df_Unplanned_Down/(60*60)

array([5.28055556])

In [25]:
df_Planned_Down = 24*60*60 -  df_Time_Diff.sum()
df_Planned_Down

25789.0

In [26]:
df_Planned_Down/(60*60)
6931/4

1732.75

In [0]:
df_Cycle = np.empty(1732)
for i in np.arange(0,1732):
  df_Cycle[i] = df_Time_Diff[4*i] + df_Time_Diff[4*i+1]+ df_Time_Diff[4*i+2]+ df_Time_Diff[4*i+3]


In [49]:
df_Cycle
df_CycleTime_count = np.empty(9633)
df_CycleTime_count

array([0.00000000e+000, 6.92762749e-310, 6.92762749e-310, ...,
       6.92765137e-310, 6.92765137e-310, 6.92765137e-310])

In [51]:
df_Cycle.astype(int)
df_CycleTime_count[77]= df_CycleTime_count[77]+ 1
df_CycleTime_count[77]

1.0

In [66]:
df_CycleTime_count = np.zeros(5000)
df_CycleTime_count = df_CycleTime_count.astype(int)
for i in df_Cycle.astype(int):
  df_CycleTime_count[i] = df_CycleTime_count[i] + 1
  print(i,df_CycleTime_count[i])

77 1
19 1
46 1
19 2
62 1
20 1
56 1
25 1
23 1
26 1
20 2
20 3
18 1
20 4
20 5
40 1
26 2
20 6
19 3
19 4
21 1
19 5
27 1
21 2
66 1
28 1
19 6
35 1
31 1
26 3
21 3
18 2
46 2
30 1
21 4
39 1
59 1
38 1
46 3
46 4
23 2
28 2
34 1
31 2
19 7
31 3
22 1
18 3
21 5
35 2
20 7
21 6
20 8
20 9
22 2
20 10
20 11
86 1
20 12
31 4
21 7
25 2
20 13
23 3
20 14
20 15
19 8
20 16
19 9
20 17
19 10
20 18
27 2
34 2
46 5
20 19
21 8
21 9
29 1
18 4
20 20
24 1
24 2
19 11
20 21
20 22
19 12
20 23
40 2
96 1
24 3
23 4
36 1
19 13
35 3
31 5
20 24
34 3
24 4
19 14
27 3
20 25
19 15
20 26
19 16
20 27
19 17
19 18
21 10
23 5
18 5
20 28
25 3
26 4
19 19
19 20
20 29
25 4
19 21
19 22
19 23
37 1
19 24
20 30
20 31
23 6
65 1
27 4
18 6
20 32
20 33
19 25
23 7
22 3
82 1
19 26
197 1
25 5
20 34
19 27
20 35
32 1
20 36
21 11
19 28
22 4
20 37
19 29
20 38
20 39
20 40
22 5
40 3
144 1
81 1
26 5
18 7
19 30
33 1
19 31
21 12
19 32
40 4
33 2
21 13
19 33
21 14
18 8
21 15
20 41
20 42
18 9
20 43
18 10
26 6
19 34
19 35
19 36
20 44
23 8
21 16
25 6
34 4
47 1
47 2
35 

In [67]:
df_CycleTime_count[22]

46

In [0]:
def largest(arr,n): 
  
    # Initialize maximum element 
    max = arr[0] 
    max_index = 0
    # Traverse array elements from second 
    # and compare every element with  
    # current max 
    for i in range(1, n): 
        if arr[i] > max: 
            max = arr[i] 
            max_index = i
    return max, max_index 

In [69]:
largest(df_CycleTime_count,5000)

(484, 19)

In [77]:
Cycle_Time = largest(df_CycleTime_count,5000)
Cycle_Time = Cycle_Time[1]/4
Cycle_Time

4.75

In [0]:
max_output = 24*60*60/ Cycle_Time
Total_Downtime = df_Planned_Down+df_Unplanned_Down
Downtime_percentage = Total_Downtime*100/(24*60*60)
Availability = 100 - Downtime_percentage

In [0]:
df_Quality = df_OEE